### ISSUE TITLE
TODO List:

### ISSUE THREAD

**Issue by Blair-Johnson** [Blair-Johnson/symbRegress#1]
- [x] Set up / find good tree data structure for doing checks and traversal
- [x] Create and store dictionary of tokens for each expression
- [x] Implement tree updating from distribution over nodes
- [x] Implement tree traversal for recovering parent and sibling node tokens
- [x] Define node characteristics (argument counts, type, terminal?)
- [x] Implement fitting constants
- [ ] Implement policy gradient/ figure out how
